name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Authenticate with Vercel
        run: vercel --auth ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel --prod
